Issue #241 Fixed all footer issues
QAZIMAAZARSHAD/Voters-Registration-Portal pull request #264
Opened 2021-06-26 19:47 UTC by Albert-Jokelin

- [x] Halved the footer grid-gap; from 4em to 2em.
- [x] Fixed the alignment issues in footer elements
- [x] Increased spacing in between elements in the footer.

Check it out: https://suspicious-clarke-a869e9.netlify.app/

2021-06-27 00:16 UTC, QAZIMAAZARSHAD commented
![Screenshot (174)](https://user-images.githubusercontent.com/56196640/123529070-c7671b00-d70a-11eb-8cbc-bc2640922254.png)

There is a large gap in top, decrease it.
And add a little padding below the copyright line.

2021-06-27 04:51 UTC, nlok5923 requested changes
PTAL

2021-06-27 04:51 UTC, nlok5923 commented on Home.html
> -
@Albert-Jokelin there are so many newline added instead of previous trailing spaces please revert this

2021-06-27 04:51 UTC, nlok5923 commented on help.css
> +
unnecessary newline

2021-06-29 18:20 UTC, Albert-Jokelin commented
I'm sorry, I got caught up with something. Will make changes right away

2021-06-30 07:45 UTC, merged

2021-06-30 07:56 UTC, QAZIMAAZARSHAD commented
@Albert-Jokelin always mention issue number like this #241 in PR description.