Issue #241 PT-2 Suggestions implemented
QAZIMAAZARSHAD/Voters-Registration-Portal pull request #291
Opened 2021-06-30 08:03 UTC by Albert-Jokelin

Issue #241

Implemented suggestions given by @nlok5923. Removed unwanted trailing spaces

2021-06-30 08:20 UTC, nlok5923 commented
@Albert-Jokelin please provide a static deployment link.

2021-06-30 08:22 UTC, Albert-Jokelin commented
Hey @nlok5923! Here's the link to the netlify page: https://suspicious-clarke-a869e9.netlify.app/

2021-07-01 03:17 UTC, nlok5923 requested changes
Thanks PTAL

2021-07-01 03:17 UTC, nlok5923 commented on form-correction.html
> -
@Albert-Jokelin there are so many redundant changes like this please revert all.

2021-07-02 09:56 UTC, closed without merging