UI Improved
QAZIMAAZARSHAD/Voters-Registration-Portal pull request #413
Opened 2021-07-22 17:50 UTC by skpandey885

#377 

UI Improved and Resonsiveness Improved!

2021-07-22 17:53 UTC, skpandey885 commented
Its shows that my branch has some conflicts can you help me how to solve this conflict issue!
@QAZIMAAZARSHAD

2021-07-22 18:17 UTC, QAZIMAAZARSHAD commented
> Its shows that my branch has some conflicts can you help me how to solve this conflict issue!
> @QAZIMAAZARSHAD

Fetch Upstream

2021-07-22 18:18 UTC, QAZIMAAZARSHAD commented
Also share the deployment link so I can review your changes.

2021-07-23 02:32 UTC, skpandey885 commented
Bhaiya the latest Changes Are Not reflecting In The Deployment link! That is the reason you were telling me that day to fetch upstream! i dont know why this is happening its just showing the chanhes it did 4 days ago and after that whatever changes im making its not reflecting there

2021-07-23 04:48 UTC, QAZIMAAZARSHAD commented
> Bhaiya the latest Changes Are Not reflecting In The Deployment link! That is the reason you were telling me that day to fetch upstream! i dont know why this is happening its just showing the chanhes it did 4 days ago and after that whatever changes im making its not reflecting there

It's because you are still a few commits behind.

Try to fetch upstream then see.
![Screenshot (109)](https://user-images.githubusercontent.com/56196640/126738524-6be69b5d-8eaf-498e-ac3c-5929da8dfd3d.png)

2021-07-23 15:52 UTC, skpandey885 commented
I did it multiple times

2021-07-23 15:55 UTC, QAZIMAAZARSHAD commented
Never forget to share the deployment link.

2021-07-23 15:57 UTC, skpandey885 commented
> Never forget to share the deployment link.
Bhaiya I think I m having some issues! I deleted the environment link and I'm cloning it again and pushing it and will generate a fresh pr!

2021-07-23 15:58 UTC, QAZIMAAZARSHAD commented
> > Never forget to share the deployment link.
> 
> Bhaiya I think I m having some issues! I deleted the environment link and I'm cloning it again and pushing it and will generate a fresh pr!

Fine.

I thought you are done.

2021-07-23 16:01 UTC, skpandey885 commented
> > > Never forget to share the deployment link.
> > 
> > 
> > Bhaiya I think I m having some issues! I deleted the environment link and I'm cloning it again and pushing it and will generate a fresh pr!
> 
> Fine.
> 
> I thought you are done.

I don't know why i am facing issues

2021-07-23 16:06 UTC, QAZIMAAZARSHAD commented
> > > > Never forget to share the deployment link.
> > > 
> > > 
> > > Bhaiya I think I m having some issues! I deleted the environment link and I'm cloning it again and pushing it and will generate a fresh pr!
> > 
> > 
> > Fine.
> > I thought you are done.
> 
> I don't know why i am facing issues

Start over again. This is the best way.

If we want to create something good we must prepare to throw our first work.

2021-07-23 16:07 UTC, QAZIMAAZARSHAD commented
If you need any help @kanak22 will help you.

2021-07-24 06:55 UTC, skpandey885 commented
bhaiya! I am seeing these errors from yesterday...check your repo of help.html file in vs code!  

<img width="1211" alt="Screenshot 2021-07-24 at 12 24 07 PM" src="https://user-images.githubusercontent.com/78532081/126860300-1d49827d-16e9-4a74-85c6-87135a76f529.png">

2021-07-24 06:57 UTC, skpandey885 commented
Bhaiya you merge this pr! bcz this pr has all the changes I made! now again I have to do all steps !

2021-07-24 10:01 UTC, nlok5923 requested changes
thanks PTAL !!

2021-07-24 10:01 UTC, nlok5923 commented on help.html
> +                    <h2 style="text-align: center; text-decoration: underline; font-family: 'Baloo Tammudu 2', cursive;">REACH US</h2>
@skpandey885 you had used inline styling most of the place please convert it to class based styling.

2021-07-28 04:55 UTC, closed without merging